version: '3'

services:
  db:
    image: mongo:5
    restart: always
    volumes:
      - ./mongo:/data/db
    container_name: mongonest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=nest-pokemon
